// Monster and UI image mappings - local paths (downloaded from imgur)
const IMAGES = {
  // UI / Boost icons
  "Information": "images/information.png",
  "Avatar": "images/avatar.png",
  "Raf": "images/raf.png",
  "Codex": "images/codex.png",
  "Slayer bxp": "images/slayer-bxp.png",
  "Combat bxp": "images/combat-bxp.png",
  "120 Slayer": "images/120-slayer.png",
  "Scrimshaw of Sacrifice": "images/scrimshaw-of-sacrifice.png",
  "Double xp": "images/double-xp.png",
  "Slayer": "images/slayer.png",
  "Off Task (GP/HR)": "images/off-task.png",
  "Combat": "images/combat.png",
  "Slayer Introspection": "images/slayer-introspection.png",
  "Binding Contracts": "images/binding-contracts.png",
  "Tetra Contracts": "images/tetra-contracts.png",
  "Misc": "images/misc.png",

  // Category icons
  "Gemstone Dragons": "images/gemstone-dragons.png",
  "Dragons": "images/dragons.png",
  "Strykewyrms": "images/strykewyrms.png",
  "Order of Ascension": "images/order-of-ascension.png",
  "Lost Grove Creatures": "images/lost-grove-creatures.png",
  "Demons": "images/demons.png",

  // Monster icons
  "Moss Golems": "images/moss-golems.png",
  "Acheron Mammoths": "images/acheron-mammoths.png",
  "Elves": "images/elves.png",
  "Shadow Creatures": "images/shadow-creatures.png",
  "Nightmares": "images/nightmares.png",
  "Lava Strykewyrms": "images/lava-strykewyrms.png",
  "Vile Blooms": "images/vile-blooms.png",
  "Crystal Shapeshifters": "images/crystal-shapeshifters.png",
  "Crocodile Akhs": "images/crocodile-akhs.png",
  "Camel Warriors": "images/camel-warriors.png",
  "Living Wyverns": "images/living-wyverns.png",
  "Corrupted Workers": "images/corrupted-workers.png",
  "Soulgazers": "images/soulgazers.png",
  "Creatures of Daemonheim": "images/creatures-of-daemonheim.png",
  "Edimmus": "images/edimmus.png",
  "Airuts": "images/airuts.png",
  "Aquanites": "images/aquanites.png",
  "Aviansies": "images/aviansies.png",
  "Chaos Giants": "images/chaos-giants.png",
  "Cresbots": "images/cresbots.png",
  "Dagannoths": "images/dagannoths.png",
  "Dark Beasts": "images/dark-beasts.png",
  "Brutish Dinosaurs": "images/brutish-dinosaurs.png",
  "Feral Dinosaurs": "images/feral-dinosaurs.png",
  "Venomous Dinosaurs": "images/venomous-dinosaurs.png",
  "Ripper Dinosaurs": "images/ripper-dinosaurs.png",
  "Black Demons": "images/black-demons.png",
  "Abyssal Demons": "images/abyssal-demons.png",
  "Abyssal Lords": "images/abyssal-lords.png",
  "Abyssal Savages": "images/abyssal-savages.png",
  "Abyssal Beasts": "images/abyssal-beasts.png",
  "Abyssal Beasts and Lords Combo": "images/abyssal-beasts.png",
  "Kal'gerion Demons": "images/kalgerion-demons.png",
  "Ripper Demons": "images/ripper-demons.png",
  "Greater Demons": "images/greater-demons.png",
  "Ash Lord Greater Demons": "images/ash-lord-greater-demons.png",
  "Tormented Demons": "images/tormented-demons.png",
  "Black Dragons": "images/black-dragons.png",
  "Celestial Dragons": "images/celestial-dragons.png",
  "Rune Dragons": "images/rune-dragons.png",
  "Adamant Dragons": "images/adamant-dragons.png",
  "Hydrix Dragons": "images/hydrix-dragons.png",
  "Nodon Dragonkin": "images/nodon-dragonkin.png",
  "Onyx Dragons": "images/onyx-dragons.png",
  "Dragonstone Dragons": "images/dragonstone-dragons.png",
  "Ganodermic Beasts": "images/ganodermic-beasts.png",
  "Gargoyles": "images/gargoyles.png",
  "Glacors": "images/glacors.png",
  "Glacytes": "images/glacytes.png",
  "Ice Strykewyrms": "images/ice-strykewyrms.png",
  "Iron Dragons": "images/iron-dragons.png",
  "Kalphites": "images/kalphites.png",
  "Mithril Dragons": "images/mithril-dragons.png",
  "Muspahs": "images/muspahs.png",
  "Mutated Jadinkos": "images/mutated-jadinkos.png",
  "Nihils": "images/nihils.png",
  "Rorarius": "images/rorarius.png",
  "Capsarius": "images/capsarius.png",
  "Steel Dragons": "images/steel-dragons.png",
  "Vyrewatch": "images/vyrewatch.png",
  "Profane Scabarites": "images/profane-scabarites.png",
  "Elite Profane Scabarites": "images/elite-profane-scabarites.png",
};

function getMonsterImage(name) {
  return IMAGES[name] || IMAGES["Information"];
}
