// Ultimate Slayer Drop Tracker - Item Data by Area
// Source: Gooch Era's Ultimate Slayer spreadsheet

var ULTIMATE_AREAS = [
  {
    id: "asgarnia_misthalin",
    name: "Asgarnia & Misthalin",
    title: "Protector of the Peace",
    drops: [
      { item: "Goblin Mail",              monster: "Goblin",                    rate: "9/128" },
      { item: "Goblin Book",              monster: "Goblin",                    rate: "Common" },
      { item: "Cornucopia",               monster: "Chicken",                   rate: "Common" },
      { item: "Off-Hand Rubber Chicken",  monster: "Chicken",                   rate: "Very Rare" },
      { item: "Crunchy Claw Token",       monster: "Mogre",                     rate: "Uncommon" },
      { item: "Mudskipper Hat",           monster: "Mogre",                     rate: "Uncommon" },
      { item: "Flippers",                 monster: "Mogre",                     rate: "Rare" },
      { item: "Granite Legs",             monster: "Skeletal Wyvern",           rate: "1/512" },
      { item: "Royal Cape",               monster: "Grotworm",                  rate: "Common" },
      { item: "Right Skull Half",         monster: "Minotaur",                  rate: "18/128" },
      { item: "Left Skull Half",          monster: "Ankou",                     rate: "3/128" },
      { item: "Top of Sceptre",           monster: "Catablepon",                rate: "4/128" },
      { item: "Bottom of Sceptre",        monster: "Flesh Crawler",             rate: "Uncommon" },
      { item: "Shade Robe (top)",         monster: "Shade",                     rate: "8/128" },
      { item: "Shade Robe (bottom)",      monster: "Shade",                     rate: "8/128" },
      { item: "Bronze Defender",          monster: "Cyclops (Champions Guild)", rate: "Uncommon" },
      { item: "Iron Defender",            monster: "Cyclops (Champions Guild)", rate: "Uncommon" },
      { item: "Steel Defender",           monster: "Cyclops (Champions Guild)", rate: "Uncommon" },
      { item: "Black Defender",           monster: "Cyclops (Champions Guild)", rate: "Uncommon" },
      { item: "Mithril Defender",         monster: "Cyclops (Champions Guild)", rate: "Uncommon" },
      { item: "Adamant Defender",         monster: "Cyclops (Champions Guild)", rate: "Uncommon" },
      { item: "Rune Defender",            monster: "Cyclops (Champions Guild)", rate: "Uncommon" },
      { item: "Dragon Defender",          monster: "Cyclops (Champions Guild)", rate: "Common" },
      { item: "Raptor Key Part 1",        monster: "Wyvern",                    rate: "1/256",    onTask: true },
      { item: "Wyvern Crossbow",          monster: "Wyvern",                    rate: "1/2000",   onTask: true },
    ]
  },
  {
    id: "daemonheim",
    name: "Daemonheim",
    title: "the Bloodrager",
    drops: [
      { item: "Adrenaline Urn",              monster: "Kal'gerion Demon",    rate: "1/1024" },
      { item: "Demon Slayer Circlet",        monster: "Kal'gerion Demon",    rate: "3/2048" },
      { item: "Demon Slayer Torso",          monster: "Kal'gerion Demon",    rate: "3/2048" },
      { item: "Demon Slayer Skirt",          monster: "Kal'gerion Demon",    rate: "3/2048" },
      { item: "Demon Slayer Boots",          monster: "Kal'gerion Demon",    rate: "3/2048" },
      { item: "Demon Slayer Gloves",         monster: "Kal'gerion Demon",    rate: "3/2048" },
      { item: "Demon Slayer Crossbow",       monster: "Kal'gerion Demon",    rate: "3/2048" },
      { item: "OH Demon Slayer Crossbow",    monster: "Kal'gerion Demon",    rate: "3/2048" },
      { item: "Kal'gerion Battle Commendation", monster: "Kal'gerion Demon", rate: "" },
      { item: "Seeker's Charm",              monster: "Seeker",              rate: "" },
      { item: "Hexhunter Bow",              monster: "Soulgazer (elite)",    rate: "1/1500" },
      { item: "Soulgazer's Charm",           monster: "Soulgazer (elite)",   rate: "" },
      { item: "Blood Necklace Shard",        monster: "Edimmu",              rate: "" },
      { item: "Edimmu Pet",                  monster: "Edimmu (elite)",      rate: "" },
    ]
  },
  {
    id: "feldip_hills",
    name: "Feldip Hills",
    title: "the Ascended",
    drops: [
      { item: "Hexcrest",                    monster: "Jungle Strykewyrm",   rate: "1/512",    onTask: true },
      { item: "Ascension Keystone",           monster: "Rorarius",            rate: "1/384" },
      { item: "Ascension Grips",             monster: "Rorarius",            rate: "1/2056",   onTask: true },
    ]
  },
  {
    id: "fremennik_province",
    name: "Fremennik Province",
    title: "the End of All Things",
    drops: [
      { item: "Light Mystic Hat",            monster: "Basilisk",                        rate: "1/512" },
      { item: "Basilisk Boots",              monster: "Basilisk",                        rate: "1/512" },
      { item: "Basilisk Head",               monster: "Basilisk",                        rate: "1/2000" },
      { item: "Light Mystic Robe Top",       monster: "Kurask",                          rate: "1/512" },
      { item: "Kurask Boots",                monster: "Kurask",                          rate: "2/128" },
      { item: "Kurask Head",                 monster: "Kurask",                          rate: "1/3000" },
      { item: "Leaf-Bladed Sword",           monster: "Kurask",                          rate: "1/128" },
      { item: "OH Leaf-Bladed Sword",        monster: "Kurask",                          rate: "1/128" },
      { item: "Light Mystic Robe Bottom",    monster: "Turoth",                          rate: "1/512" },
      { item: "Turoth Boots",                monster: "Turoth",                          rate: "1/512" },
      { item: "Light Mystic Gloves",         monster: "Rock Slug",                       rate: "1/512" },
      { item: "Light Mystic Boots",          monster: "Cockatrice",                      rate: "1/512" },
      { item: "Cockatrice Head",             monster: "Cockatrice",                      rate: "1/1000" },
      { item: "Amulet of Ranging",           monster: "Aquanite",                        rate: "1/512" },
      { item: "Brine Sabre",                 monster: "Brine Rat",                       rate: "1/512" },
      { item: "Circular Hide",               monster: "Dagannoth (Waterbirth Island)",   rate: "2/128" },
      { item: "Flattened Hide",              monster: "Dagannoth (Waterbirth Island)",   rate: "2/128" },
      { item: "Stretched Hide",              monster: "Dagannoth (Waterbirth Island)",   rate: "2/128" },
      { item: "Spined Boots",                monster: "Dagannoth (Waterbirth Island)",   rate: "20/256" },
      { item: "Spined Gloves",               monster: "Dagannoth (Waterbirth Island)",   rate: "20/256" },
      { item: "Staff of Light",              monster: "Ice Strykewyrm",                  rate: "1/512" },
      { item: "Raptor Key Part 4",           monster: "Acheron Mammoth",                 rate: "1/256",    onTask: true },
      { item: "Mammoth Tusk",                monster: "Acheron Mammoth",                 rate: "Always" },
    ]
  },
  {
    id: "kandarin",
    name: "Kandarin",
    title: "the Well 'Ardy",
    drops: [
      { item: "Tortoise Shell",          monster: "Tortoise / Warped Tortoise", rate: "Uncommon" },
      { item: "Perfect Shell",           monster: "Tortoise / Warped Tortoise", rate: "Uncommon" },
      { item: "Dragon Full Helm",        monster: "Ragged Abomination",         rate: "1/1000" },
      { item: "Chewed Bones",            monster: "Mithril Dragon",             rate: "3/128" },
      { item: "Static Gloves",           monster: "Automaton Guardian",          rate: "1/1000" },
      { item: "Tracking Gloves",         monster: "Automaton Generator",         rate: "1/1000" },
      { item: "Pneumatic Gloves",        monster: "Automaton Tracer",            rate: "1/1000" },
      { item: "Cresbot",                 monster: "Automaton (all)",             rate: "1/1600" },
      { item: "Dark Bow",                monster: "Dark Beast",                  rate: "1/1024" },
      { item: "Razorback Gauntlets",     monster: "Airut",                       rate: "1/2056",   onTask: true },
      { item: "Kaigi's Journal Page",    monster: "Airut",                       rate: "Uncommon" },
      { item: "Tuska Mask Upper Tusks",  monster: "Airut",                       rate: "1/250" },
      { item: "Tuska Mask Lower Tusks",  monster: "Airut",                       rate: "1/250" },
      { item: "Tuska Mask Headpiece",    monster: "Airut",                       rate: "1/250" },
      { item: "Tuska Mask Plate",        monster: "Airut",                       rate: "1/250" },
      { item: "Tuska Mask Top",          monster: "Airut",                       rate: "1/250" },
    ]
  },
  {
    id: "karamja",
    name: "Karamja",
    title: "of the Jungle",
    drops: [
      { item: "Dragon Platelegs",        monster: "Adamant Dragon",              rate: "1/512" },
      { item: "Dragon Plateskirt",       monster: "Adamant Dragon",              rate: "1/512" },
      { item: "Whip Vine",               monster: "Mutated Jadinko",             rate: "1/525" },
      { item: "Toktz-mej-tal",           monster: "TzHaar-Mej",                  rate: "Very Rare" },
      { item: "Toktz-xil-ul",            monster: "TzHaar-Xil",                  rate: "1/512" },
      { item: "Toktz-xil-ak",            monster: "TzHaar-Xil",                  rate: "1/1024" },
      { item: "Toktz-xil-ek",            monster: "TzHaar-Xil",                  rate: "" },
      { item: "TzHaar-Ket-Om",           monster: "TzHaar-Ket",                  rate: "" },
      { item: "Toktz-ket-xil",           monster: "TzHaar-Ket",                  rate: "" },
      { item: "Obsidian Cape",           monster: "TzHaar-Ket",                  rate: "" },
      { item: "Ring of Stone",           monster: "TzHaar-Ket",                  rate: "1/5000" },
      { item: "Gemstone Boots",          monster: "Dragonstone Dragon",          rate: "1/2048" },
      { item: "Gemstone Gauntlets",      monster: "Dragonstone Dragon",          rate: "1/2048" },
      { item: "Gemstone Helm",           monster: "Onyx Dragon",                 rate: "1/2048" },
      { item: "Gemstone Greaves",        monster: "Onyx Dragon",                 rate: "1/2048" },
      { item: "Gemstone Hauberk",        monster: "Hydrix Dragon",               rate: "1/1024" },
    ]
  },
  {
    id: "keldagrim",
    name: "Keldagrim",
    title: "the Stout Slayer",
    drops: [
      { item: "Granite Shield",              monster: "Ice Troll",                   rate: "1/128" },
      { item: "Hand Cannon",                 monster: "Chaos Dwarf Hand Cannoneer",  rate: "1/132" },
      { item: "Hand Cannon Shot",            monster: "Chaos Dwarf Hand Cannoneer",  rate: "3/132" },
      { item: "Dragon Pickaxe",              monster: "Chaos Dwarf Hand Cannoneer",  rate: "1/5000" },
      { item: "Dragon Throwing Axe",         monster: "Chaos Giant",                 rate: "3/100" },
      { item: "OH Dragon Throwing Axe",      monster: "Chaos Giant",                 rate: "3/100" },
    ]
  },
  {
    id: "kharidian_desert",
    name: "Kharidian Desert",
    title: "the Devourer",
    drops: [
      { item: "Focus Sight",                 monster: "Desert Strykewyrm",           rate: "1/512" },
      { item: "Dragon Chainbody",            monster: "Kalphite Queen",              rate: "1/128" },
      { item: "Vital Spark",                 monster: "Corrupted Creatures",         rate: "Uncommon" },
      { item: "Corrupted Gem",               monster: "Corrupted Creatures",         rate: "Very Rare" },
      { item: "Khopesh of the Kharidian",    monster: "Corrupted Creatures",         rate: "1/8000",   onTask: true },
      { item: "Key to the Crossing",         monster: "Corrupted Creatures",         rate: "1/75",     onTask: true },
      { item: "Raptor Key Part 2",           monster: "Ripper Demon",                rate: "1/256",    onTask: true },
      { item: "Ripper Claw",                 monster: "Ripper Demon",                rate: "1/2000",   onTask: true },
      { item: "OH Ripper Claw",              monster: "Ripper Demon",                rate: "1/2000",   onTask: true },
      { item: "Parasitic Orb",               monster: "Ripper Demon (elite)",        rate: "1/334" },
      { item: "Raptor Key Part 3",           monster: "Camel Warriors",              rate: "1/256",    onTask: true },
      { item: "Camel Staff",                 monster: "Camel Warriors",              rate: "1/2000",   onTask: true },
      { item: "Spectral Lens",               monster: "Profane Scabarite",           rate: "1/506",    onTask: true },
    ]
  },
  {
    id: "lost_lands",
    name: "Lost Lands",
    title: "the Harbinger of Death",
    drops: [
      { item: "Black Mask (10)",              monster: "Cave Horror",                  rate: "1/512" },
      { item: "Scare Tactics",                monster: "Unspeakable Horror",           rate: "Rare" },
      { item: "Brackish Blade",               monster: "Rum-pumped Crab",              rate: "Rare" },
      { item: "Dragon Boots",                 monster: "Spiritual Mage",               rate: "1/128" },
      { item: "Dragon Gauntlets",             monster: "Spiritual Mage",               rate: "1/256" },
      { item: "Dragon Limbs",                 monster: "Spiritual Mage",               rate: "1/256" },
      { item: "Ruined Dragon Armour Lump",    monster: "Tormented Demon",              rate: "1/1056" },
      { item: "Ruined Dragon Armour Slice",   monster: "Tormented Demon",              rate: "1/1056" },
      { item: "Ruined Dragon Armour Shard",   monster: "Tormented Demon",              rate: "1/1056" },
      { item: "Dragon Claw",                  monster: "Tormented Demon",              rate: "1/256" },
      { item: "OH Dragon Claw",               monster: "Tormented Demon",              rate: "1/256" },
      { item: "Steadfast Boots",              monster: "Glacor",                       rate: "1/1280" },
      { item: "Glaiven Boots",                monster: "Glacor",                       rate: "1/1280" },
      { item: "Ragefire Boots",               monster: "Glacor",                       rate: "1/1280" },
      { item: "Shards of Armadyl",            monster: "Glacor",                       rate: "5/48" },
      { item: "Penny",                        monster: "Shadow Creatures",             rate: "Various" },
      { item: "Seiryu's Claw",                monster: "Arhat",                        rate: "1/1024" },
      { item: "The Path of the Monk",         monster: "Anagami",                      rate: "1/16" },
      { item: "The Path of the Elemental",    monster: "Anagami",                      rate: "1/32" },
      { item: "The Path of the Dragon",       monster: "Anagami",                      rate: "1/64" },
      { item: "Cinderbane Gauntlets",         monster: "Creatures of the Lost Grove",  rate: "1/2000",   onTask: true },
      { item: "Ancient Elven Ritual Shard",   monster: "Creatures of the Lost Grove",  rate: "1/1000",   onTask: true },
      { item: "Blowpipe Chitin",              monster: "Dinosaurs",                    rate: "1/1500",   onTask: true },
      { item: "Blowpipe Feather",             monster: "Dinosaurs",                    rate: "1/1500",   onTask: true },
      { item: "Blowpipe Fins",                monster: "Dinosaurs",                    rate: "1/1500",   onTask: true },
      { item: "Bone Blowpipe",                monster: "Dinosaurs",                    rate: "1/1500",   onTask: true },
      { item: "Laceration Boots",             monster: "Dinosaurs",                    rate: "1/3000",   onTask: true },
      { item: "Blast Diffusion Boots",        monster: "Liverwort",                    rate: "1/2000",   onTask: true },
    ]
  },
  {
    id: "morytania",
    name: "Morytania",
    title: "the Scourge of the Undead",
    drops: [
      { item: "Congealed Blood",             monster: "Bloodveld",                    rate: "6/128" },
      { item: "Black Boots",                 monster: "Infernal Mage",                rate: "12/128" },
      { item: "Dark Mystic Hat",             monster: "Infernal Mage",                rate: "1/512" },
      { item: "Dark Mystic Boots",           monster: "Infernal Mage",                rate: "1/512" },
      { item: "Dark Mystic Robe Top",        monster: "Infernal Mage",                rate: "1/512" },
      { item: "Dark Mystic Robe Bottom",     monster: "Infernal Mage",                rate: "1/512" },
      { item: "Dark Mystic Gloves",          monster: "Infernal Mage",                rate: "1/512" },
      { item: "Granite Maul",                monster: "Gargoyle",                     rate: "1/512" },
      { item: "Granite Helm",                monster: "Gargoyle",                     rate: "2/512" },
      { item: "Lava Battlestaff",            monster: "Aberrant Spectre",             rate: "2/128" },
      { item: "Abyssal Whip",                monster: "Abyssal Demon",                rate: "1/1024" },
      { item: "Abyssal Wand",                monster: "Abyssal Demon",                rate: "1/6104",   onTask: true },
      { item: "Abyssal Orb",                 monster: "Abyssal Demon",                rate: "1/6104",   onTask: true },
      { item: "Abyssal Head",                monster: "Abyssal Demon",                rate: "3/16384" },
      { item: "Crawling Hand",               monster: "Crawling Hand",                rate: "1/512" },
      { item: "Ganodermic Gloves",           monster: "Ganodermic Beast",             rate: "Uncommon" },
      { item: "Ganodermic Boots",            monster: "Ganodermic Beast",             rate: "Uncommon" },
      { item: "Polypore Stick",              monster: "Ganodermic Beast",             rate: "Rare" },
      { item: "Grifolic Shield",             monster: "Grifolapine",                  rate: "Uncommon" },
      { item: "Grifolic Wand",               monster: "Grifolapine",                  rate: "Uncommon" },
      { item: "Grifolic Orb",                monster: "Grifolaroo",                   rate: "Uncommon" },
      { item: "Grifolic Gloves",             monster: "Grifolaroo",                   rate: "Uncommon" },
      { item: "Celestial Handwraps",         monster: "Celestial Dragon",             rate: "Very Rare", onTask: true },
      { item: "Dragon Rider Helm",           monster: "Celestial Dragon",             rate: "1/5120" },
      { item: "Dragon Rider Body",           monster: "Celestial Dragon",             rate: "1/5120" },
      { item: "Dragon Rider Chaps",          monster: "Celestial Dragon",             rate: "1/5120" },
      { item: "Dragon Rider Cape",           monster: "Celestial Dragon",             rate: "1/5120" },
      { item: "Dragon Rider Kit",            monster: "Celestial Dragon",             rate: "1/5120" },
    ]
  },
  {
    id: "other_worlds",
    name: "Other Worlds",
    title: "Gielinor's Champion",
    drops: [
      { item: "Dragon Ward",                  monster: "Force Muspah",                 rate: "Uncommon" },
      { item: "Dragon Knife",                 monster: "Throwing Muspah",              rate: "Uncommon" },
      { item: "OH Dragon Knife",              monster: "Throwing Muspah",              rate: "Uncommon" },
      { item: "Dragon Hasta",                 monster: "Bladed Muspah",                rate: "Uncommon" },
      { item: "Vampyre Fangs",                monster: "Blood Nihil",                  rate: "Common" },
      { item: "Icyene Feather",               monster: "Ice Nihil",                    rate: "Common" },
      { item: "Demon Horn",                   monster: "Shadow Nihil",                 rate: "Common" },
      { item: "Aviansie Talons",              monster: "Smoke Nihil",                  rate: "Common" },
      { item: "Attuned Crystal Weapon Seed",  monster: "Crystal Shapeshifter",         rate: "Uncommon" },
      { item: "Attuned Crystal Armour Seed",  monster: "Crystal Shapeshifter",         rate: "Uncommon" },
      { item: "Ancient Elven Wedding Ring",   monster: "Crystal Shapeshifter",         rate: "Very Rare" },
      { item: "Nightmare Gauntlets",          monster: "Nightmare",                    rate: "1/2000",   onTask: true },
      { item: "Steadfast Scale",              monster: "Rune Dragon",                  rate: "1/768" },
      { item: "Glaiven Wing-Tip",             monster: "Rune Dragon",                  rate: "1/768" },
      { item: "Ragefire Gland",               monster: "Rune Dragon",                  rate: "1/768" },
      { item: "Kethsi Ring (5)",              monster: "Rune Dragon",                  rate: "1/1024" },
      { item: "Kethsi Outfit Scroll",         monster: "Rune Dragon (Elite)",          rate: "" },
      { item: "Tuska's Wrath Ability Codex",  monster: "Airut",                        rate: "1/400",    onTask: true },
    ]
  },
  {
    id: "wilderness",
    name: "Wilderness",
    title: "Forinthry's Fury",
    drops: [
      { item: "Dragon Chainbody",             monster: "Kalphite Queen",               rate: "1/128" },
      { item: "Corrupt Dragon Helm",          monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Chainbody",     monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Platelegs",     monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Plateskirt",    monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Battleaxe",     monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Dagger",        monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Longsword",     monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Mace",          monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Scimitar",      monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Spear",         monster: "Revenants",                    rate: "Very Rare" },
      { item: "Corrupt Dragon Sq Shield",     monster: "Revenants",                    rate: "Very Rare" },
      { item: "Statius' Full Helm",           monster: "Revenants",                    rate: "10/90916" },
      { item: "Statius' Platebody",           monster: "Revenants",                    rate: "10/90916" },
      { item: "Statius' Platelegs",           monster: "Revenants",                    rate: "10/90916" },
      { item: "Statius' Warhammer",           monster: "Revenants",                    rate: "10/90916" },
      { item: "Vesta's Chainbody",            monster: "Revenants",                    rate: "10/90916" },
      { item: "Vesta's Plateskirt",           monster: "Revenants",                    rate: "10/90916" },
      { item: "Vesta's Longsword",            monster: "Revenants",                    rate: "10/90916" },
      { item: "Vesta's Spear",                monster: "Revenants",                    rate: "10/90916" },
      { item: "Zuriel's Hood",                monster: "Revenants",                    rate: "10/90916" },
      { item: "Zuriel's Robe Top",            monster: "Revenants",                    rate: "10/90916" },
      { item: "Zuriel's Robe Bottom",         monster: "Revenants",                    rate: "10/90916" },
      { item: "Zuriel's Staff",               monster: "Revenants",                    rate: "10/90916" },
      { item: "Morrigan's Coif",              monster: "Revenants",                    rate: "10/90916" },
      { item: "Morrigan's Leather Body",      monster: "Revenants",                    rate: "10/90916" },
      { item: "Morrigan's Leather Chaps",     monster: "Revenants",                    rate: "10/90916" },
      { item: "Morrigan's Javelin",           monster: "Revenants",                    rate: "10/90916" },
      { item: "Morrigan's Throwing Axe",      monster: "Revenants",                    rate: "10/90916" },
      { item: "Ancient Warriors' Equipment Patch", monster: "Revenants",               rate: "10/90916" },
      { item: "Revenant Spirit",              monster: "Revenants",                    rate: "Very Rare" },
      { item: "Fremennik Equipment Patch",    monster: "General Wilderness",           rate: "Very Rare" },
      { item: "Revenant Drop Enhancer",       monster: "General Wilderness",           rate: "Uncommon" },
      { item: "Wilderness Hilt",              monster: "General Wilderness",           rate: "Rare" },
      { item: "Adrenaline Crystal",           monster: "General Wilderness",           rate: "Common" },
      { item: "Wyrm Spike",                   monster: "Lava Strykewyrm",             rate: "1/6168",   onTask: true },
      { item: "Wyrm Heart",                   monster: "Lava Strykewyrm",             rate: "1/6168",   onTask: true },
      { item: "Wyrm Scalp",                   monster: "Lava Strykewyrm",             rate: "1/6168",   onTask: true },
      { item: "Greater Sonic Wave Ability Codex", monster: "Armoured Phantom",       rate: "1/1536",   onTask: true },
    ]
  },
  {
    id: "senntisten",
    name: "Senntisten",
    title: "Slayer of Senntisten",
    drops: [
      { item: "Dwarf Multicannon Upgrade Kit",  monster: "Nodon Dragonkin",            rate: "1/2000",   onTask: true },
      { item: "Kinetic Cyclone Upgrade Kit",     monster: "Nodon Dragonkin",            rate: "1/2000",   onTask: true },
      { item: "Oldak Coil Upgrade Kit",          monster: "Nodon Dragonkin",            rate: "1/2000",   onTask: true },
      { item: "Steadfast Boots",                 monster: "Nodon Dragonkin",            rate: "1/1260",   onTask: true },
      { item: "Glaiven Boots",                   monster: "Nodon Dragonkin",            rate: "1/1260",   onTask: true },
      { item: "Ragefire Boots",                  monster: "Nodon Dragonkin",            rate: "1/1260",   onTask: true },
      { item: "Abyssal Scourge",                 monster: "Abyssal Lord",               rate: "1/1280",   onTask: true },
      { item: "Jaws of the Abyss",              monster: "Abyssal Lord",               rate: "1/1280",   onTask: true },
    ]
  },
  {
    id: "general",
    name: "General",
    title: "General Drops",
    drops: [
      { item: "Tooth Half of a Key",             monster: "Various",           rate: "Common" },
      { item: "Loop Half of a Key",              monster: "Various",           rate: "Common" },
      { item: "Crystal Triskellion Fragment 1",  monster: "Various",           rate: "Varies" },
      { item: "Crystal Triskellion Fragment 2",  monster: "Various",           rate: "Varies" },
      { item: "Crystal Triskellion Fragment 3",  monster: "Various",           rate: "Varies" },
      { item: "Starved Ancient Effigy",          monster: "Various",           rate: "Very Rare" },
      { item: "Ferocious Ring (5)",              monster: "Various",           rate: "Uncommon",  onTask: true },
      { item: "Sirenic Scale",                   monster: "Various",           rate: "Uncommon" },
      { item: "Cursed Amascut Sand",             monster: "Various",           rate: "1/1024" },
      { item: "Draconic Visage",                 monster: "Dragons",           rate: "Varies" },
      { item: "Ectoplasmator",                   monster: "Undead",            rate: "Very Rare" },
      { item: "Cremation Ability",               monster: "Undead",            rate: "1/1000" },
      { item: "Deployable Herb Burner",          monster: "Various",           rate: "Very Rare" },
      { item: "Ghostly Essence",                 monster: "Various",           rate: "Varies" },
      { item: "Red Dragon Egg",                  monster: "Red Dragon",        rate: "Very Rare" },
      { item: "Blue Dragon Egg",                 monster: "Blue Dragon",       rate: "Very Rare" },
      { item: "Green Dragon Egg",                monster: "Green Dragon",      rate: "Very Rare" },
      { item: "Black Dragon Egg",                monster: "Black Dragon",      rate: "Very Rare" },
      { item: "Bone Fragments",                  monster: "Various",           rate: "Varies",    onTask: true },
    ]
  },
];
